baseURL = "https://ohio.araw.xyz"
languageCode = "en-us"
title = "to oblique lair"
enableGitInfo = true

[author]
    email = 'ohio@araw.xyz'
    name = 'ohio olarte'

[permalinks]
    log = "/:filename:"
    project = "/:filename:"
    wiki = "/:filename:"

[frontmatter]
	date = ["date", "publishDate"]
	lastmod = [":git", "lastmod", ":fileModTime", ":default"]

[markup]
  [markup.goldmark]
    [markup.goldmark.extensions]
      [markup.goldmark.extensions.passthrough]
        enable = true
        [markup.goldmark.extensions.passthrough.delimiters]
          block = [['\[', '\]'], ['$$', '$$']]
          inline = [['\(', '\)']]

[params]
  dateFormat = "2 Jan 2006"
  math = false

[privacy]
	[privacy.disqus]
		disable = true
	[privacy.googleAnalytics]
		disable = true
	[privacy.instagram]
		disable = true
	[privacy.twitter]
		disable = true
	[privacy.vimeo]
		disable = true
	[privacy.youtube]
		disable = true


