baseURL = "https://ohio.araw.xyz"
languageCode = "en-us"
title = "to oblique lair"
enableGitInfo = true

[author]
    email = "ohio@araw.xyz"
    name = "ohio olarte"

[permalinks]
    log = "/:contentbasename:"
    project = "/:contentbasename:"
    wiki = "/:contentbasename:"

[frontmatter]
    date = ["date", "publishDate"]
    lastmod = [":git", "lastmod", ":fileModTime", ":default"]

[markup]
  [markup.goldmark]
    [markup.goldmark.extensions]
      [markup.goldmark.extensions.passthrough]
        enable = true
        [markup.goldmark.extensions.passthrough.delimiters]
          block = [['\[', '\]'], ['$$', '$$']]
          inline = [['\(', '\)']]
        [markup.goldmark.renderer]
              unsafe = true
[params]
  dateFormat = "2 Jan 2006"
  math = false

[privacy]
  [privacy.disqus]
    disable = true
  [privacy.googleAnalytics]
    disable = true
    respectDoNotTrack = true
  [privacy.instagram]
    disable = true
  [privacy.vimeo]
    disable = true
    enableDNT = true
  [privacy.x]
    disable = true
    enableDNT = true
  [privacy.youTube]
    disable = true
