baseURL = "/"
languageCode = "en-us"
title = "to oblique lair"
enableGitInfo = true

[permalinks]
	log = "/:filename:"
	project = "/:filename:"

[frontmatter]
	date = ["date", "publishDate"]
	lastmod = [":git", "lastmod", ":fileModTime", ":default"]

[params]
	dateFormat = "2 Jan 2006"

[markup]
        [markup.blackFriday]
                hrefTargetBlank = true
        [markup.highlight]
                style = "friendly"

[privacy]
	[privacy.disqus]
		disable = true
	[privacy.googleAnalytics]
		disable = true
	[privacy.instagram]
		disable = true
	[privacy.twitter]
		disable = true
	[privacy.vimeo]
		disable = true
	[privacy.youtube]
		disable = true
